### ISSUE TITLE
Obvious message if "src" command not found

### ISSUE THREAD

**Issue by shagabutdinov** [sourcegraph/sourcegraph-sublime#10]
Plugin should report if "src" command not found to a new view, with brief description of the problem and a link to the website.

**Comment by samertm** [comment]
When I remove srclib from my path, a blank buffer is opened and the following exception is thrown:

Traceback (most recent call last):
  File "/home/samer/.config/sublime-text-3/Packages/sourcegraph-dev/utilities.py", line 89, in call_srclib
    data = check_output(command, env=getenv())
  File "/home/samer/.config/sublime-text-3/Packages/sourcegraph-dev/utilities.py", line 139, in check_output
    process = subprocess.Popen(stdout=subprocess.PIPE, *popenargs, **kwargs)
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'src'

**Comment by shagabutdinov** [comment]
Fixed, now report is:

````
ERROR
=====

The error was occured during execution of "src" command.

It can happen if there is not "src" command in your PATH, this means srclib was
not installed or installed incorrectly. Please, follow installation instructions
to install srclib: https://srclib.org/install/

If there is bug has occured, you can report it here: https://github.com/sourcegraph/sourcegraph-sublime/issues

Error message: [Errno 2] No such file or directory: 'src'
````

**Comment by christabella** [comment]
I'm getting this error, although `src --help` works in the terminal. Installed Fix Mac Path to align Sublime's `PATH` with that of the terminal's, but still getting the error. Does anyone know what's up?

**Comment by shagabutdinov** [comment]
Try to check sourcegraph sublime package settings and see what is in  
"which_src" setting key, probably, it points to wrong src binary. You also  
can try put here full path to "src" command. If problem still present,  
send here a full error message that sourcegraph prints to output.

On Mon, 23 Mar 2015 22:38:59 +0600, christabella  
<notifications@github.com> wrote:

> I'm getting this error, although `src --help` works in the terminal.  
> Installed Fix Mac Path to align Sublime's `PATH` with that of the  
> terminal's, but still getting the error. Does anyone know what's up?
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sourcegraph/sourcegraph-sublime/issues/10#issuecomment-85085585


-- 
Leonid Shagabutdinov
+7 905 937 6988
shagabutdinov.com

**Comment by christabella** [comment]
Thanks for your reply. Sourcegraph isn't listed in any of my Sublime
package settings. I'm using Sublime 3. Does that make a difference?

**Comment by shagabutdinov** [comment]
Not sure, sublime should add package settings to main menu, I think this  
is separate issue that should be solved in future. Probably, you can  
create Sourcegraph/Sourcegraph.sublime-settings in your "Packages" folder  
with following content:

```
{
	/* 'which_src' is the path of the 'src' binary to use. It is 'src' by  
default, which is evaluated by your shell. */
	"which_src": "src",
	/* 'gopath' overrides the environmental variable $GOPATH for running  
commands. */
	"gopath": "",
	/* 'goroot' overrides the environmental variables $GOROOT for running  
commands. */
	"goroot": "",
}
```

to be sure that "which_src" points to right "src" command.

On Tue, 24 Mar 2015 13:37:12 +0600, christabella  
<notifications@github.com> wrote:

> Thanks for your reply. Sourcegraph isn't listed in any of my Sublime
> package settings. I'm using Sublime 3. Does that make a difference?
>
> On Tue, 24 Mar 2015 at 12:06 Leonid Shagabutdinov  
> <notifications@github.com>
> wrote:
>
>> Try to check sourcegraph sublime package settings and see what is in
>> "which_src" setting key, probably, it points to wrong src binary. You  
>> also
>> can try put here full path to "src" command. If problem still present,
>> send here a full error message that sourcegraph prints to output.
>>
>> On Mon, 23 Mar 2015 22:38:59 +0600, christabella
>> <notifications@github.com> wrote:
>>
>> > I'm getting this error, although `src --help` works in the terminal.
>> > Installed Fix Mac Path to align Sublime's `PATH` with that of the
>> > terminal's, but still getting the error. Does anyone know what's up?
>> >
>> > ---
>> > Reply to this email directly or view it on GitHub:
>> >
>> https://github.com/sourcegraph/sourcegraph-sublime/issues/10#issuecomment-85085585
>>
>>
>> --
>> Leonid Shagabutdinov
>> +7 905 937 6988
>> shagabutdinov.com
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/sourcegraph/sourcegraph-sublime/issues/10#issuecomment-85330895>
>> .
>>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/sourcegraph/sourcegraph-sublime/issues/10#issuecomment-85377585


-- 
Leonid Shagabutdinov
+7 905 937 6988
shagabutdinov.com

**Comment by christabella** [comment]
Thanks again for your reply, I did that and removed and re-installed the
package. Will try a clean install of sublime...

**Comment by sporkmonger** [comment]
Actually, installing Fix Mac Path did the trick for me...

**Comment by christabella** [comment]
Sheeet... I suspect there is something highly suspect in my installation of
Sublime, then. Packages won't install properly. Thanks for the heads up!
